#!/usr/bin/env python3
"""Render the human-facing README files from catalog.yaml."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "catalog.yaml"

CATEGORIES = [
    ("brand", "brand-and-product-styles", "🔖 Brand and Product Styles", "🔖 品牌与产品风格"),
    ("general", "general-ui-design-languages", "🎨 General UI Design Languages", "🎨 通用 UI 设计语言"),
    ("game_ip_scene", "game-ip-and-scene-themes", "🎮 Game, IP, and Scene Themes", "🎮 游戏、IP 与场景主题"),
    ("reference", "reference-interfaces", "🧠 Reference Interfaces", "🧠 参考型界面"),
    ("image_layer", "image-layers", "🖼️ Image Layers", "🖼️ 图像素材层"),
    ("motion_layer", "motion-layers", "✨ Motion Layers", "✨ 动效层"),
]


def load_catalog() -> dict:
    with CATALOG_PATH.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def localized(value, lang: str):
    if isinstance(value, dict):
        return value[lang]
    return value


def cell(value: str) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ").strip()


def prose_list(values: list[str], lang: str) -> str:
    separator = "、" if lang == "zh" else ", "
    return separator.join(cell(item) for item in values)


def resource_links(resources: list[dict], lang: str) -> str:
    links = []
    for resource in resources:
        label = localized(resource["label"], lang)
        links.append(f"[{cell(label)}]({resource['url']})")
    return " · ".join(links)


def style_rows(catalog: dict, category: str, lang: str) -> list[str]:
    rows = []
    styles = sorted(
        (style for style in catalog["styles"] if style["category"] == category),
        key=lambda style: style["sort_key"].casefold(),
    )
    for style in styles:
        name = cell(style["name"][lang])
        aliases = prose_list(style["aliases"][lang], lang)
        cues = prose_list(style["visual_cues"][lang], lang)
        best_for = prose_list(style["best_for"][lang], lang)
        resources = resource_links(style["resources"], lang)
        rows.append(f"| {name} | {aliases} | {cues} | {best_for} | {resources} |")
    return rows


def quick_pick_rows(catalog: dict, lang: str, style_index: dict[str, dict]) -> list[str]:
    rows = []
    for group in catalog["quick_picks"]:
        links = []
        for style_id in group["style_ids"]:
            style = style_index[style_id]
            label = style["name"][lang]
            url = style["resources"][0]["url"]
            links.append(f"[{cell(label)}]({url})")
        rows.append(f"| {cell(group['label'][lang])} | {' · '.join(links)} |")
    return rows


def skill_rows(catalog: dict, lang: str) -> list[str]:
    rows = []
    for skill in catalog["skills"]:
        roles = prose_list(skill["roles"][lang], lang)
        summary = cell(skill["summary"][lang])
        rows.append(f"| {cell(skill['name'])} | {roles} | {summary} | [Skill]({skill['url']}) |")
    return rows


def render(catalog: dict, lang: str) -> str:
    zh = lang == "zh"
    style_index = {style["id"]: style for style in catalog["styles"]}
    counts = {key: sum(style["category"] == key for style in catalog["styles"]) for key, *_ in CATEGORIES}
    ui_count = sum(counts[key] for key in ("brand", "general", "game_ip_scene", "reference"))

    lines = [
        "<!-- Generated from catalog.yaml. Do not edit this file directly. -->",
        "",
        '<h1 align="center">Agent UI Atlas</h1>',
        "",
        (
            '<p align="center">兼顾人类浏览与 Agent 检索的 UI 设计语言、规范与技能索引。</p>'
            if zh
            else '<p align="center">A human-readable, agent-ready atlas of UI design languages, specifications, and skills.</p>'
        ),
        "",
        (
            '<p align="center"><a href="README.md">English</a> · <strong>简体中文</strong></p>'
            if zh
            else '<p align="center"><strong>English</strong> · <a href="README.zh-CN.md">简体中文</a></p>'
        ),
        "",
        '<p align="center"><a href="catalog.yaml">🤖 Agent Catalog</a> · <a href="AGENTS.md">🧭 Agent Guide</a></p>',
        "",
        (
            f'<p align="center"><sub>最后核对：<strong>{catalog["last_reviewed"]}</strong></sub></p>'
            if zh
            else f'<p align="center"><sub>Last reviewed: <strong>{catalog["last_reviewed"]}</strong></sub></p>'
        ),
        "",
        (
            f'<p align="center"><code>🧩 {ui_count} 种 UI / 参考风格</code> · <code>🖼️ {counts["image_layer"]} 种图像素材风格</code> · <code>✨ {counts["motion_layer"]} 种动效风格</code></p>'
            if zh
            else f'<p align="center"><code>🧩 {ui_count} UI/reference styles</code> · <code>🖼️ {counts["image_layer"]} image-layer styles</code> · <code>✨ {counts["motion_layer"]} motion-layer styles</code></p>'
        ),
        "",
        "## 🗺️ 目录" if zh else "## 🗺️ Contents",
        "",
        "- [按意图快速选择](#quick-picks)" if zh else "- [Quick Picks by Intent](#quick-picks)",
    ]

    for _, anchor, en_title, zh_title in CATEGORIES:
        title = zh_title if zh else en_title
        visible_title = title.split(" ", 1)[1]
        lines.append(f"- [{visible_title}](#{anchor})")
    lines.extend(
        [
            "- [Agent 设计技能](#agent-design-skills)" if zh else "- [Agent Design Skills](#agent-design-skills)",
            "- [许可与声明](#license-and-disclaimer)" if zh else "- [License and Disclaimer](#license-and-disclaimer)",
            "",
            '<a id="quick-picks"></a>',
            "",
            "## 🧭 按意图快速选择" if zh else "## 🧭 Quick Picks by Intent",
            "",
            "| 意图 | 可以从这些风格开始 |" if zh else "| Intent | Start With |",
            "|---|---|",
            *quick_pick_rows(catalog, lang, style_index),
        ]
    )

    for category, anchor, en_title, zh_title in CATEGORIES:
        lines.extend(
            [
                "",
                f'<a id="{anchor}"></a>',
                "",
                f"## {zh_title if zh else en_title}",
                "",
                (
                    "| 风格名 | 英文名 / 别名 | 视觉特征 | 适合场景 | Agent 可用资源 |"
                    if zh
                    else "| Style | Alias | Visual Cues | Best For | Agent Resources |"
                ),
                "|---|---|---|---|---|",
                *style_rows(catalog, category, lang),
            ]
        )

    lines.extend(
        [
            "",
            '<a id="agent-design-skills"></a>',
            "",
            "## 🛠️ Agent 设计技能" if zh else "## 🛠️ Agent Design Skills",
            "",
            "| 技能 | 角色 | 擅长 | 来源 |" if zh else "| Skill | Role | Best At | Source |",
            "|---|---|---|---|",
            *skill_rows(catalog, lang),
            "",
            '<a id="license-and-disclaimer"></a>',
            "",
            "## ⚖️ 许可与声明" if zh else "## ⚖️ License and Disclaimer",
            "",
        ]
    )
    if zh:
        lines.extend(
            [
                "本仓库的原创整理与文字内容采用 [知识共享署名 4.0 国际许可协议](LICENSE)。",
                "",
                "链接项目、设计规范、技能、提示词、商标、产品名称、游戏名称、截图和美术素材仍受各自权利人及许可证约束。本项目是独立参考索引，与所列品牌或权利人不存在关联、授权或赞助关系。名称中的“风格”或“灵感来源”仅表示参考方向，不授予复制受保护资产或声称官方关联的权利。",
            ]
        )
    else:
        lines.extend(
            [
                "Original curation and prose in this repository are licensed under [Creative Commons Attribution 4.0 International](LICENSE).",
                "",
                "Linked repositories, design documents, skills, prompts, trademarks, product names, game names, screenshots, and art assets remain subject to their respective owners and licenses. This project is an independent reference index and is not affiliated with, endorsed by, or sponsored by any listed brand or rights holder. A “-style” or “-inspired” label describes a reference direction; it does not grant rights to copy protected assets or claim official association.",
            ]
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when generated README files are stale")
    args = parser.parse_args()
    catalog = load_catalog()
    outputs = {
        ROOT / "README.md": render(catalog, "en"),
        ROOT / "README.zh-CN.md": render(catalog, "zh"),
    }
    stale = []
    for path, content in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(path.name)
        else:
            path.write_text(content, encoding="utf-8")
    if stale:
        print(f"Stale generated files: {', '.join(stale)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
